### ISSUE TITLE
Commit some code

### ISSUE THREAD

**Issue by caseypugh** [SimplyBen/railsfiesta#1]
Your first task is to add code to this repo!

![selfie-1](http://i.imgur.com/JXthsXB.gif)

**Comment by caseypugh** [comment]
![selfie-1](http://i.imgur.com/JXthsXB.gif)

**Comment by SimplyBen** [comment]
finally... mirrored git of my shitty blog app..I will have made 10 mistakes in this process, but at least now you can check my progress
